pipeline {
  agent any
  tools {
    maven "M3"
    jdk "JDK11"
  }
  
  stages {
    stage('Git fatch'){
      steps{
        echo 'Git fatch'
        git url: 'https://github.com/Just030/spring-petclinic.git/',
          branch: 'main', credentialsId: 'gitCredential'
      }
    }
    stage('mvn Build'){
      steps{
        echo 'Maven Build'
        sh 'mvn -Dmaven.test.failure.ignore=true clean package'
      }
    }
    stage('Docker Image'){
      steps{
        echo 'Docker Image'
      }
    }
    stage('Image Push'){
      steps{
        echo 'Image Push'
      }
    }
    stage('Codedeploy'){
      steps{
        echo 'Codedeploy'
      }
    }
  }
}
